"""Make allergy severity optional

Revision ID: 475f8d4bc16f
Revises: 7a8f4e208ffc
Create Date: 2026-09-13 21:04:38.727680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475f8d4bc16f'
down_revision: Union[str, None] = '7a8f4e208ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_allergies', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient_allergies', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###