"""Add active status to patient medications

Revision ID: 7a8f4e208ffc
Revises: 2a42c5a5f01a
Create Date: 2026-09-13 21:02:09.358895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8f4e208ffc'
down_revision: Union[str, None] = '2a42c5a5f01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_medications', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_patient_medications_active'), 'patient_medications', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_medications_active'), table_name='patient_medications')
    op.drop_column('patient_medications', 'active')
    # ### end Alembic commands ###